### ISSUE TITLE
问题反馈！

### ISSUE THREAD

**Issue by starjason** [Tallone/ishadowsocks#1]
执行 python crawler.py
有如下报错：
Traceback (most recent call last):
  File "crawler.py", line 17, in <module>
    pw = list(map(f, [pw[0],pw[2],pw[4]]))
IndexError: list index out of range

**Comment by Tallone** [comment]
哦，这个问题是你开着ss客户端了，你开着的话那个配置文件就没法修改了，你需要把客户端退了再执行

**Comment by starjason** [comment]
@Tallone 压根就没有开启客户端啊

**Comment by Tallone** [comment]
我今天晚上回去修复下

**Comment by Tallone** [comment]
已修复

**Comment by starjason** [comment]
问题貌似依旧啊

**Comment by Tallone** [comment]
你有没有同步代码？我这边测试已经没问题了

**Comment by starjason** [comment]
我是新git clone的代码 原来的删除了

**Comment by Tallone** [comment]
啊 还真奇怪 我这边测试都已经OK的了 不知道你那边为何出错

**Comment by starjason** [comment]
重新git了代码  试验了一下 还是如下错误：
`Traceback (most recent call last):
  File "crawler.py", line 22, in <module>
    pw = list(map(f, [pw[0], pw[2], pw[4]]))
IndexError: list index out of range`

在执行pip install -r requirements.txt 中出现这个：
`Downloading/unpacking beautifulsoup4==4.4.1 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB): 81kB downloaded
Requirement already satisfied (use --upgrade to upgrade): prettytable==0.7.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Downloading/unpacking requests==2.10.0 (from -r requirements.txt (line 3))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB): 506kB downloaded
Installing collected packages: beautifulsoup4, requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed beautifulsoup4 requests
Cleaning up...`

再次执行 pip install -r requirements.txt 出现这个：
`Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): prettytable==0.7.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Cleaning up...`
是否对您排查问题有帮助？

**Comment by Tallone** [comment]
噢 你是Python2.7， 我的环境是python3.5呐

**Comment by starjason** [comment]
本机有2个版本：
python -V
Python 2.7.6

python3 -V
Python 3.4.0

但是
python3 crawler.py 
Traceback (most recent call last):
  File "crawler.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by Tallone** [comment]
这个是你的问题了。看报错是你的环境有问题的
